<?php

/**
 * Function to get term name from term id
 * @param type $tid
 *      Term Id
 * @return type
 *      Term Name
 */
function get_term_name_from_tid($tid) {
    $tname = db_select('taxonomy_term_data', 'td')
            ->fields('td', array('name'))
            ->condition('td.tid', $tid)
            ->execute()->fetchField();
    return $tname;
}

function _get_last_user_from_node($nid, $is_cnt = FALSE) {
    $query = db_select("node_revision", "ur");
    $query->fields('ur', array('uid'));
    $query->condition('ur.nid', $nid);
    $query->orderBy('ur.timestamp', 'DESC');
    if ($is_cnt) {
        $result = $query->execute()->rowCount();
        return $result;
    }
    else {
        $query->range(0, 1);
        $result = $query->execute()->fetch();
        return $result->uid;
    }
}
