<?php

/**
 * Implements hook_menu().
 */
function carite_tools_menu() {
  $items = array();
  $items['admin/config/carite'] = array(
    'title' => t('Carite Settings'),
    'description' => t('Configure Carite tools Settings'),
    'page callback' => 'carite_tools_settings',
    'access arguments' => array('access administration pages'),
    'file' => 'carite_tools.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_node_insert().
 */
function carite_tools_node_insert($node) {
  switch ($node->type) {
    case 'deal_management':
      carite_tools_create_stipulation($node);
    break;
    default:
    # code...
    break;
  }
}

/**
 * @desc Auto node creation for stipulation.
 */
function carite_tools_create_stipulation($deal_node) {
  global $user;
  try {
    $terms = taxonomy_get_tree(2);
    foreach ($terms as $key => $value) {
      $node = new stdClass();
      $node->title = $deal_node->title . '-' . $value->name;
      $node->type = "stipulation_status";
      node_object_prepare($node); // Sets some defaults. Invokes hook_prepare() and hook_node_prepare().
      $node->language = LANGUAGE_NONE; // Or e.g. 'en' if locale is enabled
      $node->uid = $user->uid;
      $node->status = 1; //(1 or 0): published or not
      $node->promote = 0; //(1 or 0): promoted to front page
      $node->comment = 0; // 0 = comments disabled, 1 = read only, 2 = read/write

      // Term reference (taxonomy) field
      $node->field_refer_stipulation['und']['0']['tid'] = $value->tid;
      // Node reference field
      $node->field_refer_deal['und'][0]['nid'] = $deal_node->nid;
      $node = node_submit($node); // Prepare node for saving
      node_save($node);
    }
  } catch (Exception $e) {}
}

/**
 * Implements hook_form_alter().
 */
function carite_tools_form_alter(&$form, &$form_state, $form_id) {

}
