<?php

/**
 * Function to return number of Funded deal
 * @return type
 *      Count of Deal
 */
function get_funded_deal_count() {
  $query = db_select('node', 'n');
  $query->join('field_data_field_deal_status', 'ds', 'ds.entity_id = n.nid');
  $query->fields('n', array('nid'));
  $query->condition('ds.field_deal_status_value', 'funded');
  $cnt = $query->execute()->rowCount();
  return $cnt;
}

/**
 * Function to return number of Pending deal
 * @return type
 *      Count of Deal
 */
function get_pending_deal_count() {
  $query = db_select('node', 'n');
  $query->join('field_data_field_deal_status', 'ds', 'ds.entity_id = n.nid');
  $query->fields('n', array('nid'));
  $query->condition('ds.field_deal_status_value', 'pending');
  $cnt = $query->execute()->rowCount();
  return $cnt;
}

/**
 * @desc returns the average days to fund
 */
function get_avg_days_to_fund() {
  $total_deals = get_funded_deal_count();
  $sum = 0;
  $query = db_select('node', 'n');
  $query->join('field_data_field_date_funded', 'df', 'df.entity_id = n.nid');
  $query->join('field_data_field_date_received', 'dr', 'dr.entity_id = n.nid');
  $query->fields('df', array('field_date_funded_value'));
  $query->fields('dr', array('field_date_received_value'));
  $result = $query->execute()->fetchAll();

  foreach ($result as $key => $value) {
    $sum += strtotime($value->field_date_funded_value) - strtotime($value->field_date_received_value);
  }
  $pending = ($total_deals) ? ($sum/$total_deals) : $sum;
  return floor(($pending) / (3600*24));
}

/**
 * @desc returns the total average deals on hold.
 */
function get_total_avg_deals_onhold() {
  $total_deals = get_pending_deal_count();
  $curr_date = strtotime(date('H:i:s'));
  $sum = 0;

  $query = db_select('node', 'n');
  $query->join('field_data_field_deal_status', 'ds', 'ds.entity_id = n.nid');
  $query->join('field_data_field_date_received', 'dr', 'dr.entity_id = n.nid');

  $query->fields('dr', array('field_date_received_value'));
  $result = $query->execute()->fetchAll();

  foreach ($result as $key => $value) {
    $sum += strtotime($value->field_date_received_value) - $curr_date;
  }
  $pending = ($total_deals) ? ($sum/$total_deals) : $sum;
  return floor(($pending) / (3600*24));
}

/**
 * @desc returns the total number of funded deals
 */
function get_total_funded_deals() {
  $query = db_select('node', 'n');
  $query->join('field_data_field_advance', 'fa', 'fa.entity_id = n.nid');
  $query->join('field_data_field_deal_status', 'ds', 'ds.entity_id = n.nid');
  $query->condition('ds.field_deal_status_value', 'funded');
  $query->addExpression('SUM(field_advance_value)', 'field_advance_value');
  $total = $query->execute()->fetchField();
  return $total;
}

/**
 * @desc returns the total number of pending deals
 */
function get_total_pending_deals() {
  $query = db_select('node', 'n');
  $query->join('field_data_field_advance', 'fa', 'fa.entity_id = n.nid');
  $query->join('field_data_field_deal_status', 'ds', 'ds.entity_id = n.nid');
  $query->condition('ds.field_deal_status_value', 'pending');
  $query->addExpression('SUM(field_advance_value)', 'field_advance_value');
  $total = $query->execute()->fetchField();
  return $total;
}


/**
 * Implements hook_block_info().
 */
function carite_deal_summary_block_info() {
  $blocks = array();
  $blocks['carite_deal_summary'] = array(
    'info' => t('Deal Summary'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function carite_deal_summary_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'carite_deal_summary':
      $block['subject'] = '';
      $block['content'] = _carite_deal_summary_CONTENT();
    break;
  }
  return $block;
}

function _carite_deal_summary_CONTENT() {
  $output = '<table class="deal-summary-table">';
  $output .= '<thead>';
  $output .= '<tr>';
  $output .= '<th>FUNDED</th>';
  $output .= '<th>AVG DAYS TO FUND</th>';
  $output .= '<th>TOTAL FUNDED</th>';
  $output .= '</tr>';
  $output .= '</thead>';
  $output .= '</tbody>';
  $output .= '<tr>';
  $output .= '<td>' . get_funded_deal_count() . '</td>';
  $output .= '<td>' . get_avg_days_to_fund() . '</td>';
  $output .= '<td>$ ' . number_format(get_total_funded_deals(), 2) . '</td>';
  $output .= '</tr>';
  $output .= '</tbody>';
  $output .= '</table>';

  $output .= '<table class="deal-summary-table">';
  $output .= '<thead>';
  $output .= '<tr>';
  $output .= '<th>PENDING</th>';
  $output .= '<th>AVG DAYS ON HOLD</th>';
  $output .= '<th>TOTAL PENDING</th>';
  $output .= '</tr>';
  $output .= '</thead>';
  $output .= '</tbody>';
  $output .= '<tr>';
  $output .= '<td>' . get_pending_deal_count() . '</td>';
  $output .= '<td>' . get_total_avg_deals_onhold() . '</td>';
  $output .= '<td>$ ' . number_format(get_total_pending_deals(), 2) . '</td>';
  $output .= '</tr>';
  $output .= '</tbody>';
  $output .= '<table>';
  return $output;
}
